# Generated by Django 4.1.3 on 2022-11-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
    ]
