# Generated by Django 4.1.3 on 2022-11-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='quantity')),
                ('price', models.BigIntegerField(verbose_name='narxi')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='mahsulot nomi')),
            ],
            options={
                'verbose_name': 'Savatcha mahsulot',
                'verbose_name_plural': 'Savatchadagi mahsulotlaar',
            },
        ),
    ]
