# Generated by Django 4.1.3 on 2022-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.BigIntegerField(null=True, verbose_name='narxi'),
        ),
    ]
